-- SQL for creating or updating the courses table to support new features

-- 1. Create the courses table if it doesn't exist (ensuring all columns are present)
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    riasec_type TEXT NOT NULL CHECK (riasec_type IN ('R', 'I', 'A', 'S', 'E', 'C')),
    course_name TEXT NOT NULL,
    focus_description TEXT NOT NULL,
    what_you_learn TEXT[] DEFAULT '{}'::TEXT[],
    tools_and_skills TEXT[] DEFAULT '{}'::TEXT[],
    example_job_roles JSONB DEFAULT '[]'::JSONB,
    course_image_url TEXT,
    order_index INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    
    -- New columns for "What you'll work on" dynamic section
    work_projects TEXT,
    work_labs TEXT,
    work_collaboration TEXT,
    what_you_will_work TEXT
);

-- 2. If the table already exists, add the new columns if they are missing
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'courses' AND column_name = 'work_projects') THEN
        ALTER TABLE public.courses ADD COLUMN work_projects TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'courses' AND column_name = 'work_labs') THEN
        ALTER TABLE public.courses ADD COLUMN work_labs TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'courses' AND column_name = 'work_collaboration') THEN
        ALTER TABLE public.courses ADD COLUMN work_collaboration TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'courses' AND column_name = 'what_you_will_work') THEN
        ALTER TABLE public.courses ADD COLUMN what_you_will_work TEXT;
    END IF;
END $$;

-- 3. Policy examples (Enable RLS if not already enabled)
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Enable read access for all users" ON public.courses
    FOR SELECT USING (true);

-- Allow insert/update/delete for authenticated users (assuming teachers are authenticated)
-- Adjust 'auth.role() = ''authenticated''' based on your specific role management (e.g., specific email domain or role claim)
CREATE POLICY "Enable write access for authenticated users" ON public.courses
    FOR ALL USING (auth.role() = 'authenticated');
